### ISSUE TITLE
componente-contactos

### ISSUE THREAD

**Issue by tizon15** [SofttekFormacion2017/ghrFront#20]
Luis, en el componente contactos ¿quieres que salga en el formulario de candidatos un apartado para poder añadir el contacto desde el componente contactos o un html aparte con la lista de contactos y ademas un formulario para añadir un contacto?(como tecnologias)

**Comment by luismurciano** [comment]
los contactos deben salir dentro del  componente formulario del candidato.
durante la visualizacion (no lo hemos hecho aun) solo se muestra la lista.
Durante la edición se muestra una lista y puedes añadir, eliminar y modificar contactos

**Comment by luismurciano** [comment]
el componente principal de contacto debe contener 2 subcomponentes lista-contacto y form-contacto cuando haces click en un contacto de la lista, este modifica una variable en el componente principal que ha su vez es pasada por parametro a form-contacto (hermano de lista-contacto).
Inicialmente no se muestra ningun contacto, lista contacto tambien contiene un boton '+' para crear un contacto nuevo (id=0)

**Comment by tizon15** [comment]
Perfecto, gracias luis
